<?php
/**
 * Shared helpers for widgets that print another builder document (Loop Grid, Template).
 *
 * Not a widget: the widget registry only scans includes/Widgets/*.php.
 *
 * @package Uncoder\Builder
 */

namespace Uncoder\Builder\Widgets\Support;

use Uncoder\Builder\Core\Document;
use Uncoder\Builder\Core\Post_Types;
use Uncoder\Builder\Core\Render_Context;
use Uncoder\Builder\Plugin;

defined( 'ABSPATH' ) || exit;

/**
 * Template lookup/validation, recursion guard and editor-canvas helpers.
 */
final class Template_Embed {

	/** Maximum nesting of embedded templates (a loop item holding a template holding a loop grid…). */
	public const MAX_DEPTH = 4;

	/** @var array<int,bool> Templates being printed by an embedding widget right now. */
	private static array $stack = array();

	/**
	 * Resolves a template id to a document the current request may print.
	 *
	 * @return array{doc:?Document, error:string} error: '', 'missing', 'type', 'status'.
	 */
	public static function document( int $id, string $type, Render_Context $ctx ): array {
		// WPML / Polylang: the template's version in the language being shown (in the editor: the page's language).
		if ( $ctx->editor ) {
			$lang = \Uncoder\Builder\Site\Multilingual::language_of( $ctx->doc_id );
			$id   = '' !== $lang ? \Uncoder\Builder\Site\Multilingual::translate_id( $id, $lang ) : $id;
		} else {
			$id = \Uncoder\Builder\Site\Multilingual::translate_id( $id );
		}
		$post = $id > 0 ? get_post( $id ) : null;
		if ( ! $post instanceof \WP_Post || Post_Types::TEMPLATE !== $post->post_type || 'trash' === $post->post_status ) {
			return array(
				'doc'   => null,
				'error' => 'missing',
			);
		}
		$doc = Plugin::instance()->documents()->get( $post->ID );
		if ( ! $doc ) {
			return array(
				'doc'   => null,
				'error' => 'missing',
			);
		}
		if ( $type !== $doc->type() ) {
			return array(
				'doc'   => null,
				'error' => 'type',
			);
		}
		// The live site only shows published templates; editors preview their drafts in the canvas.
		if ( 'publish' !== $post->post_status && ! ( $ctx->editor && current_user_can( 'edit_post', $post->ID ) ) ) {
			return array(
				'doc'   => null,
				'error' => 'status',
			);
		}
		return array(
			'doc'   => $doc,
			'error' => '',
		);
	}

	/**
	 * True when printing $id here would recurse (it is already being printed, it is the edited
	 * document itself, or the nesting is too deep).
	 */
	public static function would_recurse( int $id, Render_Context $ctx ): bool {
		return isset( self::$stack[ $id ] ) || $id === $ctx->doc_id || count( self::$stack ) >= self::MAX_DEPTH;
	}

	/**
	 * Runs $callback with $ids marked as being printed.
	 *
	 * @param int[]    $ids      Template ids.
	 * @param callable $callback Callback.
	 * @return mixed Callback result.
	 */
	public static function guard( array $ids, callable $callback ) {
		$added = array();
		foreach ( $ids as $id ) {
			if ( ! isset( self::$stack[ $id ] ) ) {
				self::$stack[ $id ] = true;
				$added[]            = $id;
			}
		}
		try {
			return $callback();
		} finally {
			foreach ( $added as $id ) {
				unset( self::$stack[ $id ] );
			}
		}
	}

	/**
	 * Editor canvas: the embedded document's stylesheet. The canvas page only loads the CSS of
	 * documents the edited page referenced when it was loaded, so a newly picked template needs its own.
	 */
	public static function editor_css( Document $doc ): string {
		$css = $doc->css();
		if ( ! empty( $css['url'] ) ) {
			// phpcs:ignore WordPress.WP.EnqueuedResources.NonEnqueuedStylesheet -- editor canvas markup returned by the REST render; nothing can be enqueued there.
			return '<link rel="stylesheet" data-uncoder-doc-css="' . esc_attr( (string) $doc->id() ) . '" href="' . esc_url( add_query_arg( 'ver', $css['ver'], $css['url'] ) ) . '">';
		}
		if ( ! empty( $css['inline'] ) ) {
			// Generated by the CSS engine from sanitized settings; "<" never survives Utils::sanitize_custom_css().
			return '<style data-uncoder-doc-css="' . esc_attr( (string) $doc->id() ) . '">' . str_replace( '<', '\3C ', (string) $css['inline'] ) . '</style>';
		}
		return '';
	}

	/**
	 * Editor canvas: removes the element ids of the embedded document, so clicks inside it select the
	 * embedding widget instead of elements that do not exist in the edited document.
	 */
	public static function for_canvas( string $html ): string {
		return (string) preg_replace( '/\sdata-id="[^"]*"/', '', $html );
	}

	/**
	 * Link to edit a template in the builder (empty when the user cannot edit it).
	 */
	public static function edit_url( int $id ): string {
		if ( ! current_user_can( 'edit_post', $id ) || ! class_exists( '\Uncoder\Builder\Editor\Editor' ) ) {
			return '';
		}
		return \Uncoder\Builder\Editor\Editor::url( $id );
	}

	/**
	 * Theme Builder admin screen (empty when the user cannot manage templates).
	 */
	public static function theme_builder_url(): string {
		return current_user_can( 'edit_theme_options' ) ? admin_url( 'admin.php?page=uncoder-templates' ) : '';
	}
}
