<?php
/**
 * Shape divider library (assets/data/shapes.json, generated by tools/build-shapes.mjs).
 *
 * @package Uncoder\Builder
 */

namespace Uncoder\Builder\Core;

defined( 'ABSPATH' ) || exit;

/**
 * Each shape is drawn in a 1000×100 box with the filled area hanging from the top edge; bottom
 * dividers are the same SVG turned 180° in CSS. The editor canvas imports the same JSON.
 */
final class Shapes {

	/** @var array<string, array{label:string, invert?:bool, paths:array<int, array{d:string, o?:float}>}>|null */
	private static ?array $shapes = null;

	/**
	 * @return array<string, array{label:string, invert?:bool, paths:array<int, array{d:string, o?:float}>}>
	 */
	public static function all(): array {
		if ( null === self::$shapes ) {
			$file         = UNCODER_WB_PATH . 'assets/data/shapes.json';
			$data         = is_readable( $file ) ? json_decode( (string) file_get_contents( $file ), true ) : null; // phpcs:ignore WordPress.WP.AlternativeFunctions.file_get_contents_file_get_contents
			self::$shapes = is_array( $data ) ? $data : array();
		}
		return self::$shapes;
	}

	/**
	 * Select options: name => label.
	 *
	 * @return array<string,string>
	 */
	public static function options(): array {
		return array_map( static fn( $s ) => (string) $s['label'], self::all() );
	}

	/**
	 * Shapes that have a negative (inverted) version.
	 *
	 * @return string[]
	 */
	public static function invertible(): array {
		return array_keys( array_filter( self::all(), static fn( $s ) => ! empty( $s['invert'] ) ) );
	}

	public static function exists( string $name ): bool {
		return isset( self::all()[ $name ] );
	}

	/**
	 * Inline SVG. The negative version fills the rest of the box (even-odd with the full box).
	 */
	public static function svg( string $name, bool $invert = false ): string {
		$shape = self::all()[ $name ] ?? null;
		if ( ! $shape ) {
			return '';
		}
		$invert = $invert && ! empty( $shape['invert'] );
		$paths  = '';
		foreach ( $shape['paths'] as $path ) {
			$attrs = '';
			if ( $invert ) {
				$attrs .= ' fill-rule="evenodd"';
			}
			if ( isset( $path['o'] ) ) {
				$attrs .= ' opacity="' . (float) $path['o'] . '"';
			}
			$paths .= '<path class="uncoder-shape__fill"' . $attrs . ' d="' . esc_attr( ( $invert ? 'M0 0H1000V100H0Z' : '' ) . $path['d'] ) . '"/>';
		}
		return '<svg viewBox="0 0 1000 100" preserveAspectRatio="none" aria-hidden="true" focusable="false">' . $paths . '</svg>';
	}
}
